### PR TITLE
Audio Downloader for Icelandic (islex.is)

### PR DESCRIPTION
**Pull request by belteshassar**
So, I wrote this downloader class for Icelandic but I can't get it to work in Anki. Anyone has any ideas about why it's failing?

Edit: The string to search for is `field_data.word` Got it working. Will push working version soon.

### CODE REVIEW

**Comment by belteshassar** [comment]
Pushed working version.

**Comment by ospalh** [comment]
Looks good at  first glance. Thanks.
I’ll take a closer look soon.

**Comment by ospalh** [comment]
I have pushed a bit more clean-up to this on [my branch](https://github.com/ospalh/anki-addons/tree/feature-islex). Maybe you want to use that when you sort out the mp3 thing.

**Comment by ospalh** [comment]
I just pick the type (audio/mp3) now on my branch. I will test this a bit and then probably merge my branch. No need for you to change to mp3, too.
Thanks again for the work.

**Comment by ospalh** [comment]
One thing that could be changed, is this: When you enter a word without diacritics (“dottir”) that should be spelled with (“dóttir’) the one with gets downloaded. Ideally, the display string and file name base strings should be changed. See for example the [`leo.py`](https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/downloaders/leo.py#L128) downloader that sets the value of `DownloadEntry.word`.
(This is a “would be nice” feature. I will probably merge this without it.)

**Comment by belteshassar** [comment]
Cool. Thanks for cleaning up my mess :) I thought about changing the display name. Will pull your changes and take a look at it and see what I can come up with. Just have to find the right tag I guess...

Could also be nice to put the gender in the extras so I might do that as well. Is there any other info you put in the extras normally? I guess I could figure that out from the German downloaders since German is probably the language with the most similar grammar.

I also thought about making a search for the exact match first (fuzz=0) and then running the search with fuzz=1 if no match was found the first time. That's probably also the reason I left the except for no results in there. Couldn't decide if that would be helpful or confusing so I'll probably leave it as is.

**Comment by belteshassar** [comment]
> One thing that could be changed, is this: When you enter a word without diacritics (“dottir”) that should be spelled with (“dóttir’) the one with gets downloaded. Ideally, the display string and file name base strings should be changed.

I think my last two updates fix this. I set `entry.word`, will that fix both the display string and file name base string?

**Comment by ospalh** [comment]
> ll. Is there any other info you put in the extras normally?

Putting the gender and the the part of speech there is great. :+1:  for the changes.

I use the extras dict for several things, basically whatever i got back besides the actual audio that i thought users might find useful, greping thorough the downloaders:
* Beolingus: part of speech
* Duden: Copyright
* Japanesepod: The “popular” tag when using the WWWJDIC and when that tag is set there
* MacMillan: The “Alt Text:” is used for e.g. the second entry for “house”. (That one still makes me smile.)  I may have to look into it why the value there is empty.
* Meriam Webster: Meaning number. E.g. for row vs. row.
* OALD: The “Title”. Can’t remember what that was about, tbh.
* Forvo (not in the published version): Name and gender of the speaker, language, rating.


> I think my last two updates fix this. I set entry.word, will that fix both the display string and file name base string?

[Yes](https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/download_entry.py#L38-L44). And thanks for that cange, too. :+1:

**Comment by ospalh** [comment]
Thanks again. I have now tested on all three platforms and it works.

**Comment by ospalh** [comment]
Btw, the bit about the gender is gone again? I saw in one intermediate version that you added the gender to the extras. I wanted to fix the spelling, use “Gender” instead of “gender” (It’s on its own line, so like the beginning of a sentence), but couldn’t find it in the final version.

**Comment by belteshassar** [comment]
> the bit about the gender is gone again?

I realized that gender is put in the same tag as part of speech for non-nouns. I just put whatever is in that tag under 'Type'.

**Pull request merged**
