### PR TITLE
Port downloadaudio to Anki 2.1

### PR DESCRIPTION
**Pull request by marciomazza**
### What I did

I completely port the Download Audio add-on until I couldn't find any bug.

I did not test other add-ons, but incidentally made these broad changes to all codebase:
* some porting from PyQt4 to PyQt5
* some `2to3` fixes
* porting to BeautfulSoup 4 (the version used by Anki)

I used these references as guides:
* http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html
* the main porting commit from Anki itself: https://github.com/dae/anki/commit/de7e4

Please note that I do not know PyQt and this is the first time I see Anki's or this repo's source, so mistakes are expected. I tried my best though, to make at least downloadaudio work.

### Points I suggest you revise

* The uses of `BeautifulSoup` constructor, especially the occurences of `BeautifulSoup(text, 'html.parser')`. Maybe they should use another parser.
* Some suppressions I made of encoding/decoding strings. I removed only parts which where causing bugs by changed semantics on python 3

### CODE REVIEW

**Comment by ospalh** [comment]
Thanks.
It is at least a great starting point. And possibly some will work just like this. For those, this will be just great. 😄 
As i noted, i don't exactly get one of your changes. I'll deal with that some time later.
Anyway, I'll just merge this now.

**Comment by ospalh** [comment]
Oh, there is one change i should do before i release these:
I should credit you in the file headers. 😄 
(Unless you explicitly say you don't want to.)

**Comment by ospalh** [comment]
One more point:
I stuck to BS, even though i find the name rather fitting, because that is what Anki itself uses. I know that BS will be there. Easier than bringing your own parser along.

**Comment by marciomazza** [comment]
The bug in  `WiktionaryDownloader` was actually caused by this line:
https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/downloaders/downloader.py#L134
which expects self.url to be just a prefix.
Before the fix it, when this line was executed, `self.url` would have the value `http://{0}.wiktionary.org/wiki/{1}`. The language part `{0}` had to be resolved by then.

All the rest of the downloaders treat `AudioDownloader.url` as a prefix, so now `WiktionaryDownloader` goes along.

The property setter for `WiktionaryDownloader.url` is necessary because without it the line
https://github.com/ospalh/anki-addons/blob/develop/downloadaudio/downloaders/downloader.py#L55
would raise an exception.

**Comment by marciomazza** [comment]
Thanks for the credit and for the add-on. It really makes a difference on my study.

**Comment by ospalh** [comment]
Did you really see any problems without turning `url` into a property?
Because the line you pointed to should *not* be called for `WiktionaryDownloader`/`wiktionary.py`, because that reimplements `maybe_get_icon()`, the function you pointed to.

**Comment by marciomazza** [comment]
It was called when I was testing.

Em 30 de nov de 2016 9:57 AM, "ospalh" <notifications@github.com> escreveu:

**Comment by marciomazza** [comment]
Maybe you could run it without that commit and see what you get.

Em 30 de nov de 2016 10:04 AM, "Marcio Mazza" <marciomazza@gmail.com>
escreveu:

**Comment by ospalh** [comment]
Well, i [can’t](https://ospalh.github.io/anki-addons/2016/11/30/Python_3.html) run it with Anki 2.1/Python3, and with Anki 2.0/Python 2 it is fetching the wiktionary site icon.

**Comment by marciomazza** [comment]
Yes... I found it difficult to set up Anki 2.1.

If you want any help, I'm here.

Em 30 de nov de 2016 10:13 AM, "ospalh" <notifications@github.com> escreveu:

**Pull request merged**
